# Labels
__RESOURCE_TYPE__ = "STRUCTURAL"

# Library import
import sys
import os

# Constants definition
ConfigurationsTable = {   'shared.communication_architecture.layers.communication.modules.client': {   'SERVER_PROFILES': {   'DESCRIPTION': 'It '
                                                                                                                       'includes '
                                                                                                                       'a '
                                                                                                                       'list '
                                                                                                                       'of '
                                                                                                                       'ServerProfile '
                                                                                                                       'instances, '
                                                                                                                       'with '
                                                                                                                       'information '
                                                                                                                       'to '
                                                                                                                       'search '
                                                                                                                       'it '
                                                                                                                       'to '
                                                                                                                       'establish '
                                                                                                                       'a '
                                                                                                                       'connection',
                                                                                                        'OPTIONAL': False,
                                                                                                        'PRIVATE': False,
                                                                                                        'SYMBOLIC_NAME': 'Server '
                                                                                                                         'profiles',
                                                                                                        'SYSTEM_NAME': 'SERVER_PROFILES',
                                                                                                        'VALUE': {   'DATA_CLASS': True,
                                                                                                                     'DATA_TYPE': 'list',
                                                                                                                     'DESCRIPTION': None,
                                                                                                                     'MAXIMUM_LENGTH': None,
                                                                                                                     'MINIMUM_LENGTH': 1,
                                                                                                                     'NAME': 'Server '
                                                                                                                             'Collection',
                                                                                                                     'POSSIBLE_VALUES': [   {   '__type__': 'ComplexData',
                                                                                                                                                'content': {   'DATA_CLASS': True,
                                                                                                                                                               'DATA_TYPE': 'dict',
                                                                                                                                                               'DESCRIPTION': None,
                                                                                                                                                               'MAXIMUM_LENGTH': None,
                                                                                                                                                               'MINIMUM_LENGTH': None,
                                                                                                                                                               'NAME': 'INTERNET '
                                                                                                                                                                       'Profile',
                                                                                                                                                               'POSSIBLE_VALUES': {   'ADDRESSES': {   '__type__': 'ComplexData',
                                                                                                                                                                                                       'content': {   'DATA_CLASS': True,
                                                                                                                                                                                                                      'DATA_TYPE': 'list',
                                                                                                                                                                                                                      'DESCRIPTION': None,
                                                                                                                                                                                                                      'MAXIMUM_LENGTH': None,
                                                                                                                                                                                                                      'MINIMUM_LENGTH': 1,
                                                                                                                                                                                                                      'NAME': 'IP '
                                                                                                                                                                                                                              'List',
                                                                                                                                                                                                                      'POSSIBLE_VALUES': [   {   '__type__': 'ComplexData',
                                                                                                                                                                                                                                                 'content': {   'DATA_CLASS': True,
                                                                                                                                                                                                                                                                'DATA_TYPE': 'dict',
                                                                                                                                                                                                                                                                'DESCRIPTION': None,
                                                                                                                                                                                                                                                                'MAXIMUM_LENGTH': None,
                                                                                                                                                                                                                                                                'MINIMUM_LENGTH': None,
                                                                                                                                                                                                                                                                'NAME': 'IP '
                                                                                                                                                                                                                                                                        'Endpoint',
                                                                                                                                                                                                                                                                'POSSIBLE_VALUES': {   'ADDRESS': [   {   '__type__': 'PrimitiveData',
                                                                                                                                                                                                                                                                                                          'content': {   'DATA_CLASS': True,
                                                                                                                                                                                                                                                                                                                         'DATA_TYPE': 'str',
                                                                                                                                                                                                                                                                                                                         'DESCRIPTION': 'IPv4 '
                                                                                                                                                                                                                                                                                                                                        'address',
                                                                                                                                                                                                                                                                                                                         'MAXIMUM_LENGTH': 15,
                                                                                                                                                                                                                                                                                                                         'MAXIMUM_SIZE': None,
                                                                                                                                                                                                                                                                                                                         'MINIMUM_LENGTH': 7,
                                                                                                                                                                                                                                                                                                                         'MINIMUM_SIZE': None,
                                                                                                                                                                                                                                                                                                                         'NAME': 'IPv4 '
                                                                                                                                                                                                                                                                                                                                 'address',
                                                                                                                                                                                                                                                                                                                         'POSSIBLE_VALUES': None,
                                                                                                                                                                                                                                                                                                                         'REGULAR_EXPRESSION': '^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$',
                                                                                                                                                                                                                                                                                                                         'VALUE': '192.168.0.1',
                                                                                                                                                                                                                                                                                                                         '__type__': 'PrimitiveData'}},
                                                                                                                                                                                                                                                                                                      {   '__type__': 'PrimitiveData',
                                                                                                                                                                                                                                                                                                          'content': {   'DATA_CLASS': True,
                                                                                                                                                                                                                                                                                                                         'DATA_TYPE': 'str',
                                                                                                                                                                                                                                                                                                                         'DESCRIPTION': 'IPv6 '
                                                                                                                                                                                                                                                                                                                                        'address',
                                                                                                                                                                                                                                                                                                                         'MAXIMUM_LENGTH': 39,
                                                                                                                                                                                                                                                                                                                         'MAXIMUM_SIZE': None,
                                                                                                                                                                                                                                                                                                                         'MINIMUM_LENGTH': 2,
                                                                                                                                                                                                                                                                                                                         'MINIMUM_SIZE': None,
                                                                                                                                                                                                                                                                                                                         'NAME': 'IPv6 '
                                                                                                                                                                                                                                                                                                                                 'address',
                                                                                                                                                                                                                                                                                                                         'POSSIBLE_VALUES': None,
                                                                                                                                                                                                                                                                                                                         'REGULAR_EXPRESSION': '^(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))$',
                                                                                                                                                                                                                                                                                                                         'VALUE': None,
                                                                                                                                                                                                                                                                                                                         '__type__': 'PrimitiveData'}},
                                                                                                                                                                                                                                                                                                      {   '__type__': 'PrimitiveData',
                                                                                                                                                                                                                                                                                                          'content': {   'DATA_CLASS': True,
                                                                                                                                                                                                                                                                                                                         'DATA_TYPE': 'str',
                                                                                                                                                                                                                                                                                                                         'DESCRIPTION': 'Domain '
                                                                                                                                                                                                                                                                                                                                        'name',
                                                                                                                                                                                                                                                                                                                         'MAXIMUM_LENGTH': None,
                                                                                                                                                                                                                                                                                                                         'MAXIMUM_SIZE': None,
                                                                                                                                                                                                                                                                                                                         'MINIMUM_LENGTH': None,
                                                                                                                                                                                                                                                                                                                         'MINIMUM_SIZE': None,
                                                                                                                                                                                                                                                                                                                         'NAME': 'Domain '
                                                                                                                                                                                                                                                                                                                                 'name',
                                                                                                                                                                                                                                                                                                                         'POSSIBLE_VALUES': None,
                                                                                                                                                                                                                                                                                                                         'REGULAR_EXPRESSION': '^(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\\.)+[a-zA-Z]{2,}$',
                                                                                                                                                                                                                                                                                                                         'VALUE': None,
                                                                                                                                                                                                                                                                                                                         '__type__': 'PrimitiveData'}}],
                                                                                                                                                                                                                                                                                       'PORT': [   {   '__type__': 'PrimitiveData',
                                                                                                                                                                                                                                                                                                       'content': {   'DATA_CLASS': True,
                                                                                                                                                                                                                                                                                                                      'DATA_TYPE': 'int',
                                                                                                                                                                                                                                                                                                                      'DESCRIPTION': 'Internet '
                                                                                                                                                                                                                                                                                                                                     'port '
                                                                                                                                                                                                                                                                                                                                     'on '
                                                                                                                                                                                                                                                                                                                                     'the '
                                                                                                                                                                                                                                                                                                                                     'range '
                                                                                                                                                                                                                                                                                                                                     'from: '
                                                                                                                                                                                                                                                                                                                                     '1, '
                                                                                                                                                                                                                                                                                                                                     'to: '
                                                                                                                                                                                                                                                                                                                                     '65,535',
                                                                                                                                                                                                                                                                                                                      'MAXIMUM_LENGTH': None,
                                                                                                                                                                                                                                                                                                                      'MAXIMUM_SIZE': 65535,
                                                                                                                                                                                                                                                                                                                      'MINIMUM_LENGTH': None,
                                                                                                                                                                                                                                                                                                                      'MINIMUM_SIZE': 1,
                                                                                                                                                                                                                                                                                                                      'NAME': 'Internet '
                                                                                                                                                                                                                                                                                                                              'port',
                                                                                                                                                                                                                                                                                                                      'POSSIBLE_VALUES': None,
                                                                                                                                                                                                                                                                                                                      'REGULAR_EXPRESSION': None,
                                                                                                                                                                                                                                                                                                                      'VALUE': 24450,
                                                                                                                                                                                                                                                                                                                      '__type__': 'PrimitiveData'}}]},
                                                                                                                                                                                                                                                                'VALUE': {   'ADDRESS': '192.168.0.1',
                                                                                                                                                                                                                                                                             'PORT': 24450},
                                                                                                                                                                                                                                                                '__type__': 'ComplexData'}}],
                                                                                                                                                                                                                      'VALUE': [   {   'ADDRESS': '192.168.0.1',
                                                                                                                                                                                                                                       'PORT': 24450}],
                                                                                                                                                                                                                      '__type__': 'ComplexData'}},
                                                                                                                                                                                      'TRANSPORT': [   'INTERNET']},
                                                                                                                                                               'VALUE': {   'ADDRESSES': [   {   'ADDRESS': '192.168.0.1',
                                                                                                                                                                                                 'PORT': 24450}],
                                                                                                                                                                            'TRANSPORT': 'INTERNET'},
                                                                                                                                                               '__type__': 'ComplexData'}},
                                                                                                                                            {   '__type__': 'ComplexData',
                                                                                                                                                'content': {   'DATA_CLASS': True,
                                                                                                                                                               'DATA_TYPE': 'dict',
                                                                                                                                                               'DESCRIPTION': None,
                                                                                                                                                               'MAXIMUM_LENGTH': None,
                                                                                                                                                               'MINIMUM_LENGTH': None,
                                                                                                                                                               'NAME': 'BLUETOOTH '
                                                                                                                                                                       'Profile',
                                                                                                                                                               'POSSIBLE_VALUES': {   'ADDRESSES': {   '__type__': 'ComplexData',
                                                                                                                                                                                                       'content': {   'DATA_CLASS': True,
                                                                                                                                                                                                                      'DATA_TYPE': 'list',
                                                                                                                                                                                                                      'DESCRIPTION': None,
                                                                                                                                                                                                                      'MAXIMUM_LENGTH': None,
                                                                                                                                                                                                                      'MINIMUM_LENGTH': 1,
                                                                                                                                                                                                                      'NAME': 'BT '
                                                                                                                                                                                                                              'List',
                                                                                                                                                                                                                      'POSSIBLE_VALUES': [   {   '__type__': 'ComplexData',
                                                                                                                                                                                                                                                 'content': {   'DATA_CLASS': True,
                                                                                                                                                                                                                                                                'DATA_TYPE': 'dict',
                                                                                                                                                                                                                                                                'DESCRIPTION': None,
                                                                                                                                                                                                                                                                'MAXIMUM_LENGTH': None,
                                                                                                                                                                                                                                                                'MINIMUM_LENGTH': None,
                                                                                                                                                                                                                                                                'NAME': 'BT '
                                                                                                                                                                                                                                                                        'Endpoint',
                                                                                                                                                                                                                                                                'POSSIBLE_VALUES': {   'ADDRESS': [   {   '__type__': 'PrimitiveData',
                                                                                                                                                                                                                                                                                                          'content': {   'DATA_CLASS': True,
                                                                                                                                                                                                                                                                                                                         'DATA_TYPE': 'str',
                                                                                                                                                                                                                                                                                                                         'DESCRIPTION': 'MAC '
                                                                                                                                                                                                                                                                                                                                        'address',
                                                                                                                                                                                                                                                                                                                         'MAXIMUM_LENGTH': None,
                                                                                                                                                                                                                                                                                                                         'MAXIMUM_SIZE': 17,
                                                                                                                                                                                                                                                                                                                         'MINIMUM_LENGTH': None,
                                                                                                                                                                                                                                                                                                                         'MINIMUM_SIZE': 17,
                                                                                                                                                                                                                                                                                                                         'NAME': 'MAC '
                                                                                                                                                                                                                                                                                                                                 'address',
                                                                                                                                                                                                                                                                                                                         'POSSIBLE_VALUES': None,
                                                                                                                                                                                                                                                                                                                         'REGULAR_EXPRESSION': '^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$',
                                                                                                                                                                                                                                                                                                                         'VALUE': None,
                                                                                                                                                                                                                                                                                                                         '__type__': 'PrimitiveData'}}],
                                                                                                                                                                                                                                                                                       'PORT': [   {   '__type__': 'PrimitiveData',
                                                                                                                                                                                                                                                                                                       'content': {   'DATA_CLASS': True,
                                                                                                                                                                                                                                                                                                                      'DATA_TYPE': 'int',
                                                                                                                                                                                                                                                                                                                      'DESCRIPTION': 'Internet '
                                                                                                                                                                                                                                                                                                                                     'port '
                                                                                                                                                                                                                                                                                                                                     'on '
                                                                                                                                                                                                                                                                                                                                     'the '
                                                                                                                                                                                                                                                                                                                                     'range '
                                                                                                                                                                                                                                                                                                                                     'from: '
                                                                                                                                                                                                                                                                                                                                     '1, '
                                                                                                                                                                                                                                                                                                                                     'to: '
                                                                                                                                                                                                                                                                                                                                     '65,535',
                                                                                                                                                                                                                                                                                                                      'MAXIMUM_LENGTH': None,
                                                                                                                                                                                                                                                                                                                      'MAXIMUM_SIZE': 65535,
                                                                                                                                                                                                                                                                                                                      'MINIMUM_LENGTH': None,
                                                                                                                                                                                                                                                                                                                      'MINIMUM_SIZE': 1,
                                                                                                                                                                                                                                                                                                                      'NAME': 'Internet '
                                                                                                                                                                                                                                                                                                                              'port',
                                                                                                                                                                                                                                                                                                                      'POSSIBLE_VALUES': None,
                                                                                                                                                                                                                                                                                                                      'REGULAR_EXPRESSION': None,
                                                                                                                                                                                                                                                                                                                      'VALUE': None,
                                                                                                                                                                                                                                                                                                                      '__type__': 'PrimitiveData'}}]},
                                                                                                                                                                                                                                                                'VALUE': None,
                                                                                                                                                                                                                                                                '__type__': 'ComplexData'}}],
                                                                                                                                                                                                                      'VALUE': None,
                                                                                                                                                                                                                      '__type__': 'ComplexData'}},
                                                                                                                                                                                      'TRANSPORT': [   'BLUETOOTH']},
                                                                                                                                                               'VALUE': None,
                                                                                                                                                               '__type__': 'ComplexData'}}],
                                                                                                                     'VALUE': [   {   'ADDRESSES': [   {   'ADDRESS': '192.168.0.1',
                                                                                                                                                           'PORT': 24450}],
                                                                                                                                      'TRANSPORT': 'INTERNET'}],
                                                                                                                     '__type__': 'ComplexData'}}},
    'system.install.modules.persistence_crontab_linux': {   'EXECUTION_INTERVAL': {   'DESCRIPTION': 'Specify the '
                                                                                                     'interval between '
                                                                                                     'executions of '
                                                                                                     'the software',
                                                                                      'OPTIONAL': False,
                                                                                      'PRIVATE': False,
                                                                                      'SYMBOLIC_NAME': 'Execution '
                                                                                                       'interval',
                                                                                      'SYSTEM_NAME': 'EXECUTION_INTERVAL',
                                                                                      'VALUE': {   'DATA_CLASS': True,
                                                                                                   'DATA_TYPE': 'int',
                                                                                                   'DESCRIPTION': None,
                                                                                                   'MAXIMUM_LENGTH': None,
                                                                                                   'MAXIMUM_SIZE': None,
                                                                                                   'MINIMUM_LENGTH': 0,
                                                                                                   'MINIMUM_SIZE': None,
                                                                                                   'NAME': None,
                                                                                                   'POSSIBLE_VALUES': None,
                                                                                                   'REGULAR_EXPRESSION': None,
                                                                                                   'VALUE': 100,
                                                                                                   '__type__': 'PrimitiveData'}}}}
    
# Classes definition
class ConfigurationsManager:
    _instance = None

    def __new__(cls):
        """Implementación de Singleton para acceso global único."""
        if cls._instance is None:
            cls._instance = super(ConfigurationsManager, cls).__new__(cls)
            # Al inicializarse, ya tiene acceso a la tabla inyectada
            cls._instance._table = ConfigurationsTable
        return cls._instance

    def query_configuration(self, element_name: str) -> dict:
        """Recupera la configuración de un elemento por su identificador único."""
        return self._table.get(element_name, {})

    def get_all(self) -> dict:
        """Retorna la base de datos completa de configuración."""
        return self._table
